se ru nohls
se modeline
se ts=4 sw=4 sts=4 et
se so=5
se bg=dark mouse=
execute pathogen#infect()
syn on
" filetype plugin indent on

nmap <NL> <Plug>BookmarkToggle
nmap <C-Up> <Plug>BookmarkPrev
nmap <C-Down> <Plug>BookmarkNext
let g:bookmark_highlight_lines = 1

let g:gitgutter_override_sign_column_highlight = 0
highlight clear SignColumn
highlight GitGutterAdd ctermfg=2
highlight GitGutterChange ctermfg=3
highlight GitGutterDelete ctermfg=1

let NERDTreeIgnore = [ '\.o$', '\.d$' ]

" disable autoindent if F8 is hit
nmap <F8> :setl noai nocin nosi inde=<CR>
